# 1) كتابة ملف الأتمتة الذي سيصنع كل شيء ويبني الـ APK تلقائياً
mkdir -p .github/workflows && cat << 'EOF' > .github/workflows/build_apk.yml
name: Build Family Tree APK

on:
  push:
      branches: [ "main" ]
        workflow_dispatch:

        jobs:
          build:
              runs-on: ubuntu-latest
                  steps:
                        - name: Checkout Code
                                uses: actions/checkout@v3

                                      - name: Set up Java & Flutter
                                              uses: subosito/flutter-action@v2
                                                      with:
                                                                flutter-version: '3.19.0'
                                                                          channel: 'stable'

                                                                                - name: Auto Create Project & Build
                                                                                        run: |
                                                                                                  flutter create --org com.aldkheel --project-name family_tree_app base_project
                                                                                                            cp genealogy_canvas_widget.dart base_project/lib/
                                                                                                                      cat << 'EXTRA' > base_project/lib/main.dart
                                                                                                                                import 'package:flutter/material.dart';
                                                                                                                                          import 'genealogy_canvas_widget.dart';
                                                                                                                                                    void main() => runApp(MaterialApp(
                                                                                                                                                                debugShowCheckedModeBanner: false,
                                                                                                                                                                            home: Scaffold(body: SafeArea(child: GenealogyCanvas(elementsJson: '{}', onElementsChanged: (json) async => null))),
                                                                                                                                                                                      ));
                                                                                                                                                                                                EXTRA
                                                                                                                                                                                                          cd base_project
                                                                                                                                                                                                                    flutter pub get
                                                                                                                                                                                                                              flutter build apk --release

                                                                                                                                                                                                                                    - name: Upload APK
                                                                                                                                                                                                                                            uses: actions/upload-artifact@v3
                                                                                                                                                                                                                                                    with:
                                                                                                                                                                                                                                                              name: release-apk
                                                                                                                                                                                                                                                                        path: base_project/build/app/outputs/flutter-apk/app-release.apk
                                                                                                                                                                                                                                                                        EOF

                                                                                                                                                                                                                                                                        # 2) تحديث ملف الشجرة إلى النسخة 4 المطورة (الترس، الإطارات، التوقيع الجديد)
                                                                                                                                                                                                                                                                        cat << 'EOF' > genealogy_canvas_widget.dart
                                                                                                                                                                                                                                                                        // ============================================================================
                                                                                                                                                                                                                                                                        // GenealogyCanvasWidget.dart — نسخة 4 (تطبيق حسين الدخيل المطور)
                                                                                                                                                                                                                                                                        // ============================================================================

                                                                                                                                                                                                                                                                        import 'dart:convert';
                                                                                                                                                                                                                                                                        import 'dart:math' as math;
                                                                                                                                                                                                                                                                        import 'package:flutter/material.dart';

                                                                                                                                                                                                                                                                        enum ElementType { trunk, branch, leaf }
                                                                                                                                                                                                                                                                        enum FrameStyle { classic, modern, royal }

                                                                                                                                                                                                                                                                        class ExportSettings {
                                                                                                                                                                                                                                                                          String topText;
                                                                                                                                                                                                                                                                            String familyLineageText;
                                                                                                                                                                                                                                                                              FrameStyle frameStyle;

                                                                                                                                                                                                                                                                                ExportSettings({
                                                                                                                                                                                                                                                                                    this.topText = 'وَجَعَلْنَاكُمْ شُعُوباً وَقَبَائِلَ لِتَعَارَفُوا',
                                                                                                                                                                                                                                                                                        this.familyLineageText = 'نسب عائلة آل الدخيل - عشيرة عبادة',
                                                                                                                                                                                                                                                                                            this.frameStyle = FrameStyle.classic,
                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                Map<String, dynamic> toJson() => {
                                                                                                                                                                                                                                                                                                        'topText': topText,
                                                                                                                                                                                                                                                                                                                'familyLineageText': familyLineageText,
                                                                                                                                                                                                                                                                                                                        'frameStyle': frameStyle.name,
                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                factory ExportSettings.fromJson(Map<String, dynamic> json) => ExportSettings(
                                                                                                                                                                                                                                                                                                                                        topText: json['topText'] as String? ?? '',
                                                                                                                                                                                                                                                                                                                                                familyLineageText: json['familyLineageText'] as String? ?? '',
                                                                                                                                                                                                                                                                                                                                                        frameStyle: FrameStyle.values.firstWhere(
                                                                                                                                                                                                                                                                                                                                                                  (e) => e.name == (json['frameStyle'] as String? ?? 'classic'),
                                                                                                                                                                                                                                                                                                                                                                            orElse: () => FrameStyle.classic,
                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                          class TreeElement {
                                                                                                                                                                                                                                                                                                                                                                                            String id;
                                                                                                                                                                                                                                                                                                                                                                                              ElementType type;
                                                                                                                                                                                                                                                                                                                                                                                                double x;
                                                                                                                                                                                                                                                                                                                                                                                                  double y;
                                                                                                                                                                                                                                                                                                                                                                                                    double width;
                                                                                                                                                                                                                                                                                                                                                                                                      double height;
                                                                                                                                                                                                                                                                                                                                                                                                        double rotation;
                                                                                                                                                                                                                                                                                                                                                                                                          bool locked;
                                                                                                                                                                                                                                                                                                                                                                                                            String text;
                                                                                                                                                                                                                                                                                                                                                                                                              String? parentId;
                                                                                                                                                                                                                                                                                                                                                                                                                Color color;

                                                                                                                                                                                                                                                                                                                                                                                                                  TreeElement({
                                                                                                                                                                                                                                                                                                                                                                                                                      required this.id,
                                                                                                                                                                                                                                                                                                                                                                                                                          required this.type,
                                                                                                                                                                                                                                                                                                                                                                                                                              required this.x,
                                                                                                                                                                                                                                                                                                                                                                                                                                  required this.y,
                                                                                                                                                                                                                                                                                                                                                                                                                                      this.width = 140,
                                                                                                                                                                                                                                                                                                                                                                                                                                          this.height = 160,
                                                                                                                                                                                                                                                                                                                                                                                                                                              this.rotation = 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.text = '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.locked = false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.parentId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Color? color,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }) : color = color ?? _defaultColorFor(type);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  static Color _defaultColorFor(ElementType type) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      switch (type) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case ElementType.trunk: return const Color(0xFF6B4226);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  case ElementType.branch: return const Color(0xFF8A5A33);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        case ElementType.leaf: return const Color(0xFF4C8C4A);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Map<String, dynamic> toJson() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'id': id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'type': type.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'x': x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'y': y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'width': width,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'height': height,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'rotation': rotation,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'text': text,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'locked': locked,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'parentId': parentId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'color': color.value,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                factory TreeElement.fromJson(Map<String, dynamic> j) => TreeElement(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id: j['id'] as String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: ElementType.values.firstWhere((e) => e.name == j['type']),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        x: (j['x'] as num).toDouble(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                y: (j['y'] as num).toDouble(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: (j['width'] as num?)?.toDouble() ?? 140,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height: (j['height'] as num?)?.toDouble() ?? 160,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rotation: (j['rotation'] as num?)?.toDouble() ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text: j['text'] as String? ?? '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        locked: j['locked'] as bool? ?? false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parentId: j['parentId'] as String?,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: j['color'] != null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        